server:
  port: 8181
  servlet:
    context-path: /routes

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}

spring:
  application:
    name: ms-routes
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://95.163.237.3:5432/wtg_db?currentSchema=routes_ms
    username: wtg
    password: wtg
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
