server:
  port: 8179
  servlet:
    context-path:
  forward-headers-strategy: framework

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: ms-locations-events-1
          uri: lb://ms-locations-events
          predicates:
            - Path=/locations-events/**
        - id: ms-routes-1
          uri: lb://ms-routes
          predicates:
            - Path=/routes/**
        - id: ms-auth-1
          uri: lb://ms-auth
          predicates:
              - Path=/auth/**